### ISSUE TITLE
Doc: domains, layouts, database data

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#101]

**Comment by ivanarrizabalaga** [comment]
Integration with readthedocs almost ready. 
Preparing contents

**Comment by ivanarrizabalaga** [comment]
- Layouts hierarchy (runtime views not included yet)
 - Domain model
 - Sql data example

**Comment by ifoche** [comment]
As long as I can see, only DB UML chart is done, but there's no UML chart for the rest of the app, isn't it?

**Comment by adrianq** [comment]
@ivanarrizabalaga @ifoche In a lucid chart there can be multiple tabs (diagrams). There is no point to create a new file. It makes more sense to create new tabs in the "Malaria DB" file as the topic is quite similar. I was having a look at the diagrams @ivanarrizabalaga has just created. Why do we need a "Database Sample Data" diagram? It is just something you can look with any db client. Is not "MalariaCare Domain UML" almost the same we already had? If it is about adding the methods (which I don't think it is a good idea to have in the diagram as at the moment it is work in progress changing quite rapidly). Anyway, why don't we use the one already created? Why do we have to create one from scratch? Btw, the arrows are wrong. In a 1 to N relation the arrow should be pointing to the N (or is it different because is a UML diagram?). Why some fields have a minus at beginning of the line while others have a plus?

**Comment by ivanarrizabalaga** [comment]
Hi, sorry for the 'brick', @adrianq @ifoche

## Quick response ##

+1 to use tabs instead of more documents I didn't know this feature.
+1 some arrows without the right visibility flag ( + or - )  (i will clean this up)

## Explanations ##

The 'sample' diagram is extremely useful (at least for me), sure I could end up having the same info by browsing the tables but now I got a big picture just in a glance.

For instance, I was browsing the database tables (especially answer, value, option) for a while and there was still something not really clear to me.

After putting all the data together (1 open question 
+ 1 dropdown question) everything was ok and I could even see some more interesting info (understanding 'uids', seeing that 'user' table is not working yet, and so...)

The domain classes diagram pretty much reflect the same info than the db diagram, for sure, but there are differences for example:

  - A domain class diagram shows the public API that you can use to interact with your data. Many times there are calculated attributes or methods that cannot be seen in a database model.

 - Those tables that are only required to resolve a N x M relationship many times does not map to any class.

The arrows are ok, just like you said, in a DB diagram the arrow goes from the slave table to the master table. In the UML diagram I'm using simple association (the class with the attribute points to the referenced class) and aggregations whenever a class references many objects of a different class.

**Comment by adrianq** [comment]
@ivanarrizabalaga Ok, understood. Obviously to write down the content of the db can be useful but maybe it is sth that can be done in a sheet of paper. Perhaps, imho, it doesn't worth the effort of writing it as a Lucid Chart. Regarding, the db UML diagram I appreciate your point although, again, I am not sure if it worth the effort when we don't have any NxM (correct me if I am wrong) and the API is quite sort. Anyway, no regrets as it is already done and can be useful in the future. Thank you for the explanation!

**Comment by ivanarrizabalaga** [comment]
@adrianq I've just added the sample data as a tab to the db diagram.

I cannot put all the diagrams into one doc since there is a limit of 60 objects/doc with the free tier.

There will be 2 docs, one for the db (model and data) and one for the app (the one you already had + the domain classes)
