### ISSUE TITLE
Test whether programs are accepting blank eventDate through the API

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1088]

**Comment by ifoche** [comment]
This task would imply:
- [ ] Force a blank on eventDate just before uploading the event, and check whether the event is uploaded or receives a conflict
- [ ] Protect pull from blank event dates. Just discard them, do not try to translate those events
- [ ] If the API is accepting blanks, protect also from pushing blanks (first, discard and prevent the user with a Toast if the event has a blank eventDate, then try to figure out why are they being produced)
- [ ] Check every onResume and onRestart to be sure nothing there is creating the blanks

**Comment by idelcano** [comment]
1- The blank event date can be uploaded from the app without any conflict or problem.
2- The  surveys without eventdate not cause crash, it shows "-" in the improve date. Anyway i changed it to not pull  events without event date.
3- At this moment: 
-When the app uploads a survey without eventdate, a dialog shows a message to inform the user with the eventUID.
4-I think the problem was in the ProgressActivity push. In this push the surveys was sent without completionDate.
