### ISSUE TITLE
scroll optimisation

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1145]

**Comment by adrianq** [comment]
Scroll has improved dramatically however when a parent question is about to be displayed the scroll gets stuck for a couple of seconds. We need to analyse what is going on here.  If it has to do with the database maybe a cache may help?

**Comment by ivanarrizabalaga** [comment]
Notes:

| Type              | Avg time |
|-------------------|----------|
| header            | 1ms      |
| label             | 1ms      |
| Radio group       | 5ms      |
| Dropdown          | 5ms      |
| Dropdown disabled | 20/25ms  |

The ones taken extra time to render are the dropdown with matches since its value is settled in the getview instead of before

**Comment by ivanarrizabalaga** [comment]
A 'dropdown disabled' item rewrites its value everytime a *getView* is invoked which is the reason why the scroll lags a little bit.

The method **autoFillAnswer** should be removed and replace for something different while the parent match question is being selected.

**Comment by adrianq** [comment]
Closing this card. I have created a specific card (#1161) to deal just with the performance of the match questions. It is the only big issue left in terms of performance.
