### ISSUE TITLE
Bugs on eds.psi-mis.org

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1365]
- [x] Last survey date bug. On Mali -> Mopti -> BANKASS -> CSRef BANKASS last survey on 2017 is not shown in the app
- [x] Problem with scores calculation. [Adherence tab not working](https://drive.google.com/open?id=0B7TXlu17DcAbZURDc21yemVsSE1PUHd6VVI5cUthS2lRYlVN) while [Gen OTSS does work](https://drive.google.com/open?id=0B7TXlu17DcAbRHNQNVZFVDZPaGQtWkUyM2lnUnhxOG1qU3Fn)

**Comment by idelcano** [comment]
- "Last survey date bug. On Mali -> Mopti -> BANKASS -> CSRef BANKASS last survey on 2017 is not shown in the app"
1. The problem was use the lastUpdated date to find the last events, solved using the eventDate

- " Problem with scores calculation. Adherence tab not working while Gen OTSS does work"
2. The problem with the compositeScores is fixed in the last version on 2.22 compatibility branch. But i create a new PR with a little change from hnqis ( if the CS root not exist, set the CS root as 0).

Anyway the compositeScores hierarchical codes of these CS are wrong

The codes in the server:
Pharmacy/Clinical Register to Lab Result bUuUOl78Zil hierarchical_code = 1
Positive Test Result LMOy2lBAvnA hierarchical_code = 2
Negative Test Result LPXuC9zQHHq hierarchical_code = 3

Should be:
Pharmacy/Clinical Register to Lab Result bUuUOl78Zil hierarchical_code = 0
Positive Test Result LMOy2lBAvnA hierarchical_code = 1
Negative Test Result LPXuC9zQHHq hierarchical_code = 2


PD:
I found these invalid dataElements with a worng question type attribute value (ignored in the app):
        JcUr3Qtmy5A
        Jb72CVvIQEM
        VOoTU22Wgdb
        qrfzX0Q71Lt
        ESItl7EAA8m
        K7fBXcczsJU
        xtAndPQgiPx
        GNHpLiddK4s
        oMtOdo8ARhj
        QV3TWA8wyRR
        elXyFyPjapU
        lYY0VLGtQC6
        UYtLbGaUSp3
        bauf5IXPs3I
