### ISSUE TITLE
implement onResume() in every Activity

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#163]

**Comment by ivanarrizabalaga** [comment]
According to android docs there is no need to finish every activity before raising an intent to start another activity.

In terms of performance/memory the android core is in charge of destroying/recreating activities when is required.

I have tried to implement the flow like this, not finishing any activity and using onRestart to dinamically reload data into adapters but (probably due to the nested listview in dashboard activity) I couldnt manage to make it work.

What I have finally accomplished is a cleaner version of the current code:

 - Dashboard, Details, Create and Survey: finish themselves when navigating to other activity (except when going to settings)
 - Dashboard, Details, Create and Survey onBackPressed to gack to Dashboard
 - LoginActivity is resumed without recreation.
