### ISSUE TITLE
Email to Simen/Lars about attributes in the SDK

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#170]

**Comment by ifoche** [comment]
Jose, I think emails are much more things that can go in the Trello board. This is more for code. Maybe here, if it is related to an existing issue (or you can create an issue related to the code) you can put it there as a comment. May I label this issue as "invalid" and create an issue for you in the Trello board?

**Comment by josemp10** [comment]
Should't be the same case that the questions that we had for Rodolfo? (they
were opened as several issues in the waffle). The code we have to write
will depend on the Simen/Lars answer ... Anyway, it doesn' t really matter
to me... so wherever you think appropiate, it is fine to me...

**Comment by ifoche** [comment]
If that was the case, I think we did it wrong. If the code depends on that, we should have an issue talking about the code modification that we may do, and there, write a comment saying that we need to email Simen/Lars. I don't know if you see my point, and of course we can decide it together. The point is that the code is the code, and the waffle/github must represent the coding tasks that we have in our plans. When you come to the waffle you have to see the work, or at least, you need to have an easy filter that shows you the work. Otherwise, you don't have a clear picture of what you've got in your hands, and that would affect the time estimations you could give to your clients.
I'm not saying everything I did in the past was correct. Please note that until this release we were using a "Planning for Release X" to organize priorities and from now on we've changed to using the labels "Maximum priority", "Medium priority" and "Low priority".  So we realized something was not being well done (in this case something that I did) and we corrected it, no matter who proposed it, or who have done it. 
So, for providing that realistic picture, I think we can :
- Use the label "question" we already have
- Create a new label (i.e. "email")
- Use the "EyeSeeTea Collaborators" board on Trello

What of these ones do you prefer? Do you have another proposal?

What do the rest of the team think? @EyeSeeTea/developers ?

**Comment by ifoche** [comment]
I've chosen the 1st: use the label "question" we already have. That way no one must change his habits and we have a way to differentiate between coding work and "administrative" work

**Comment by ifoche** [comment]
@josemp10 , what is the state of this issue?

**Comment by ifoche** [comment]
anyone out there? If I get no answer in a week, I'll close this issue. I'll use this break week in the project development to clean up all the issues that has been accumulating all this time, and may have no sense anymore

**Comment by josemp10** [comment]
Yes, we postpone this task till we have an answer from PSI saying Yes/No to
the pull

**Comment by ifoche** [comment]
ok, thanks!

**Comment by ifoche** [comment]
Hi there, so we have a "yes" now. Are we in the right situation for restarting this task?

**Comment by ifoche** [comment]
@josemp10 did you have the time to look at this task?

**Comment by josemp10** [comment]
No, not yet sorry. I know I have to do it asap. Will send the email in the
following days, or even will meet them here in MZ,
