### ISSUE TITLE
Comp. Scores for auto-answered questions are not being calculated properly

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#478]
In fact, it does not matter if the answer is 'Yes' or 'No', they are going to sum the point

**Comment by ivanarrizabalaga** [comment]
@josemp10, this should be a data issue, dont you think? If a given question has no points it must be a 0 /0 (num/den).

**Comment by josemp10** [comment]
The options that we have in the database for auto answered questions are:

260;'Yes [1]';'Yes';1.00;89
261;'No [0]';'No';0.00;89

However, even if the answer is 'No', the user gets a point.

**Comment by adrianq** [comment]
@ivanarrizabalaga We will talk about this on Monday but definitively this is sth we need to have a look at..

**Comment by ivanarrizabalaga** [comment]
Match question has some points associated (sounds logical)

**Question**


| id_question | /form    | /num | /den  | /id_composite_score |
|---------------|-----------|-------|--------|--------------------|
| 22            | Diagnosis | 0     | 0      | -                  |
| 23            | Treatment | 0     | 0      | -                  |
| 24            | Matches   | 0.25  | 0.25   | 6                  |



**Option**


| id_option | /name | /factor |
|-----------|-------|---------|
| 256       | Oui   | 1       |
| 257       | Non   |         |

But there are 2 different problems:

 - **ScoreRegister.getCompositeScore**: Sums twice the numerator/denominator  since getRecursiveScore calls *calculateNumDenTotal* too.

 - **AutoTabLayoutUtils.autoFillAnswer** is not adding the record for the match question to the ScoreRegister, thus no matter what answer are you giving there are no points for it.
