### ISSUE TITLE
Push also the score classification with each survey

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#481]

**Comment by ifoche** [comment]
The UID of the dataElement that store this classification is:
ggrkfoq6nxA

**Comment by ifoche** [comment]
Apparently, there will be, apart from that dataElement, other 3 boolean dataElements to push representing :
- If the survey is A class
- If the survey is B class
- If the survey is C class
(yes, I know this sounds very strange but...)

@josemp10 will provide the UIDs for these dataElements soon

**Comment by josemp10** [comment]
Here they are:

_Overall Class A: TgCWRlUXbca


_Overall Class B: zckZqXOQRHT


_Overall Class C: DBUwlPCO0Hd

**Comment by ivanarrizabalaga** [comment]
@adrianq, @josemp10 just be sure, these 4 elements should be posted just like any other dataElemet?
```json
{
   ...
   dataValues: [
      {dataElement:"6s7df88d", value:"true"}
   ]
}
```

**Comment by josemp10** [comment]
Yep

**Comment by adrianq** [comment]
Yes, [this is how I calculated it](https://github.com/EyeSeeTea/malariapp/blob/2bf88433c5e66cd14dd12df8743cbb81a9726560/app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java#L197-L200) although this code was never released because of a bug in DHIS. If you follow the code, [this is how it is pushed to the server](https://github.com/EyeSeeTea/malariapp/blob/2bf88433c5e66cd14dd12df8743cbb81a9726560/app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java#L377-L379).
