### ISSUE TITLE
Include Unit Tests

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#50]

**Comment by ifoche** [comment]
- [ ] Unit test:
   - [ ] Compositive scores
   - [ ] General Scores
   - [ ] Layout automatic tab
   - [ ] Layout custom tab
   - [ ] Db

**Comment by ifoche** [comment]
Hi Ivan, would you be available for a meeting tomorrow (Tue 19) afternoon to review how are we going with the progress on this task? I was thinking on something like 16h, but please let me know if you prefer a different hour.

**Comment by ivanarrizabalaga** [comment]
@ifoche Sure, tomorrow 16h.

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers
Finally a basic coverage with tests is merged with development.

I thought that scores could be a great place for unit tests but it can not be done like that right now since the code has strong dependencies with Android stuff (adapters updating views, recovering data from sqlite and so.)

I decided to cover some of the scoring with instrumented tests checking subtotals of a tab and the score tab.
