### ISSUE TITLE
Questions for Rodolfo

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#54]
- [ ] Do we need login system? What permissions do we have to check?
- [ ] Do we support multisurveys?
- [ ] Do we ask Org units/program/period is information at the beginning of the process? At the end?
- [ ] If the survey starts on a specific day but finishes on a different one. Which period will be assigning to this survey?
- [ ] Do we allow to create orgunit and program locally and then create a sort of matching process once we have internet connectivity?
- [ ] Do we need to store the user locally so that this information is pushed to DHIS when committing this information? Maybe not for this, but in order to show the user the drafted surveys that he created previouly?
- [ ] How are we going to implement custom questions?
- [x] What sort of information are we going to push? Are we pushing scores and/or question-answer? Scores for Microscopy 1/Microscopy 2/Microscopy 3/ Microscopy aggregated? Scores for manual and automatic question?
- [x] Deadlines and planning?

**Comment by josemp10** [comment]
Answers to those questions:

- Do we need login system? What permissions do we have to check?

Yes, only to access to the DHIS2 API. One tablet only has one user. The permissions of the user will be managed by DHIS2.

- Do we support multisurveys?

Yes. One user may manage different surveys at the same time. Some of them may be incompleted (s/he could not have the time to answer all the question), other complete... The org. unit and the date identify one survey for the app.

- Do we ask Org units/program/period is information at the beginning of the process? At the end?

At the beginning. However, we should store the completion date as well. A survey is complete when the user answers all the questions (so yes, it seems the user needs to answer all of them), so the completion date can be automatically calculated. So, one survey will have org. unit, event_date, completion_date as metadata.

-  If the survey starts on a specific day but finishes on a different one. Which period will be assigning to this survey?

Answered in the previous question. We need to store both, but the completion_date is the one that is going to be pushed to DHIS2 as metadata.

- Do we allow to create orgunit and program locally and then create a sort of matching process once we have internet connectivity?

No for programs. But for org. units it may be a good idea to implement that case in the future, we need to think about it (right now, it is not a priority).

- Do we need to store the user locally so that this information is pushed to DHIS when committing this information? Maybe not for this, but in order to show the user the drafted surveys that he created previouly?

Likely it is going to be a good idea. Again, this is going to be pretty simple as we don´t have to implement something like a user management module. One tablet (one app) only has one user. But within the user table we can store some settings for the user (login, locale, ...)

- How are we going to implement custom questions?

As they are right now. As we are going to push also the scores (tab scores, compositive scores), we also need to create them in the database (likely in one table 'scores' similar to the 'questions' one) to store their UID.

- What sort of information are we going to push? Are we pushing scores and/or question-answer? Scores for Microscopy 1/Microscopy 2/Microscopy 3/ Microscopy aggregated? Scores for manual and automatic question?

We are pushing: scores (tab scores, compositive scores), and the answers to all the questions (it does not matter if they are options, dates, free text, numbers). We are not pushing numerators, denominatores, intermidiate scores...

- Deadlines and planning?

We don´t have a deadline for this (pushing data to DHIS2) yet. It can be June or July. Our following deadline will be on the 15 th or 20th of April to implement other stuff :) (and we need to talk about it). Anyway the answers to those questions are very important as they define the scope of many things in the database that we need to keep in mind.

I will leave this issue open for further discussions.
