### ISSUE TITLE
pull-not-finishing bug

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#540]
The pull works the first time (after login).

After that a pull under demand looks like loads all the stuff but somehow the data taken from the server is made of nulls.

If you logout an try to login again the pull doesnt crash the app but it looks like it is not completely finished.

**Comment by ifoche** [comment]
second time that we call pull this doesn't end

**Comment by ivanarrizabalaga** [comment]
The sequence of calls are:

 - system/info
 - me/programs

N times (1 x program):

 - system/info
 - programs/<<uid>>?fields=....

And finally the optionsets and options

 - system/info
 - optionSets?paging=false...

After a little change now it works for the first and after demand but somehow it looks it is not working with a logout +login again.

I need to check this out, anyway I'm adding a new commit since it is a improvement from the previous commit.
