### ISSUE TITLE
Goto login if pull fail

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#597]
If the pull fails, the application show a model dialog with the error, but if you press OK, the application dont do nothing... but the progress bar still "loading...".
If press ok, the app should go to the login.

**Comment by ivanarrizabalaga** [comment]
@ifoche when a pull crashes you go to login because there is nothing you can do with that, but when it is a push you can probably go back to dashboard and keep on working normally.

Does that make sense to you?? 

Pull crash -> login
Push crash -> dashboard

Or go to login (losing not sent surveys) in any case?

**Comment by ifoche** [comment]
@ivanarrizabalaga, you're completely right. Aborting a push shouldn't take you to login.
