### ISSUE TITLE
Push 9999 dataElement

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#600]
There is an additional dataValue that needs to be sent during the push:

_Forward Order DE -> '9999'

**Comment by ivanarrizabalaga** [comment]
@josemp10, do you know the UID of this control element??

**Comment by ifoche** [comment]
@josemp10, I think you didn't read this message, could you please create the control dataElement in the server side and tell us its UID? Thank you

**Comment by josemp10** [comment]
Sorry for the slow response

uid: d1At6VgPNA6

Same configuration in the server than the other Control Data Elements

**Comment by ifoche** [comment]
@josemp10 I've uploaded the control dataElement push but I cannot see in the server side, could you check that we're properly receiving them?

**Comment by ifoche** [comment]
BTW I cannot even see any value for the DEs _Overall Class A/B/C,  should I?

**Comment by josemp10** [comment]
@ignacio, those dataelements are not visible from the web interface
anymore... Can you let me know the program/s and org. units you are pushing
to? (I am travelling today, but will look at it later)

**Comment by ifoche** [comment]
@josemp10 It was the ICM program (I think it was called something like IMCI
or something like that. It is the only one I have permissions for that is
not HIV nor family planning). The org unit is the testing 1 (the only one I
have permissions for). I uploaded 3 out 4 surveys yesterday 5/12  that
should have that field set.

Thank you very much

**Comment by josemp10** [comment]
See the attached screen, it seems that the _Push ControlDataElement is not
being pushed... The Class A, B, and C are ok. Also the _Overall score?

[image: Inline image 1]

**Comment by josemp10** [comment]
You can see the dataelemenet: here
https://hnqis.psi-mis.org/api/dataElements/d1At6VgPNA6

**Comment by ifoche** [comment]
@josemp10 I cannot see your image. However, it's strange because there's no difference at all in how I'm pushing that DE in the code (in fact, it is a copy&paste from the code that pushes the other DEs that you're mentioning and it is not a complicated code, 4 lines exactly). Are you sure you're looking to the surveys I uploaded yesterday? I'm including as the payload of the DV the string "9999", is it ok?

**Comment by ifoche** [comment]
@josemp10 I've just uploaded a survey to each of the 3 programs I have access to (HIV, family planning and IMCI). The dataElement I'm uploading is d1At6VgPNA6, and in every case I'm putting 9999 as the payload...I don't know what else to do...

**Comment by ifoche** [comment]
Hi again @josemp10. I'm so sorry, it was completely my fault. I was changing the new control dataElement in the part of the code that uploads it using the API calls, and not using the SDK...so that's why it was not there. 

I've made the change in the SDK part and uploaded 1 survey of each type that I have permissions. Can you recheck? I'm really sorry for wasting your time.

**Comment by ifoche** [comment]
And if you don't wan't to continue wasting your time, don't even check it. I've looked at the server and it seems the dataValue is there. Just forget about this issue.

**Comment by josemp10** [comment]
Yes, the data is there. Thanks!
