### ISSUE TITLE
Document DBFLow lazy issue

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#625]
Document an issue related to dbflow lazy annotations, currently is not working as documented.

**Comment by ifoche** [comment]
May [this](https://github.com/Raizlabs/DBFlow/issues/349) be the same problem that we have? Maybe commenting directly there would be more efficient.

**Comment by ivanarrizabalaga** [comment]
This task cannot be fully done right now (not without wasting a little bit of time).
According to the issue, this should be fixed en 3.0.0 but this version has not been published in jcenter yet.

This is what I have done:

 - Check the contents of the issue 
 - Check that the problem remains the same (fk still null)
 - Check new releases of the lib, there should be 2.3.0 and 3.0.0, where this one should fixed the lazy stuff according to a maintainer's comment.
 - None of this tags are ready to use via dependency.
 - Try to install locally but found that only 2.3.0 is built and the number of jars to include has changed ( 'com.raizlabs.android:dbflow-core:2.3.0', 'com.raizlabs.android:dbflow-processor:2.3.0')
 - Add mavenLocal() and change dbflow versions but another error show up.

**Comment by ifoche** [comment]
Hi @ivanarrizabalaga, the problem of upgrading DBFlow to 3.0.0 is that SDK is pointing to 2.2 as well, so we would create problems with the SDK part. However even if we cannot upgrade yet and even if we cannot get the thing working now, the task was more about commenting into that issue (if the issue is exactly the same) or creating a new one (if it's not), telling the main developer the exact error we're having, with the example code you did, just to let him know that we're here and with the same issue, and get his feedback (to know if there's something we're not aware about this problem. Could you do that?

**Comment by ivanarrizabalaga** [comment]
@ifoche, sure.

The issue and the code that has been posted in it matches the sample that I did a couple of months ago (names of VOs are different that the rest is the same).

I've just added a comment on the issue to check its real status and see what to expect.
It looks like in a best case scenario the issue will be fixed in 3.0.0 and that wont be very useful for us in short term. :(

Let's wait for an answer...
