### ISSUE TITLE
Monitor Tab

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#638]

**Comment by ifoche** [comment]
![monitor_tab](https://cloud.githubusercontent.com/assets/10931645/11702187/fd6a9d04-9ed4-11e5-94d7-52bd0ea7414f.png)

![monitor_tab_2](https://cloud.githubusercontent.com/assets/10931645/11702188/01be215a-9ed5-11e5-9c1c-c027373e2963.png)

**Comment by ifoche** [comment]
- Introduce filter for pie charts to select by program

**Comment by idelcano** [comment]
I was having troubles with the click in the webview, the problem was not in the tabHost, the problem was  i was  still using listfragment. I changed it to Fragment and it works fine. 

The problem was caused by setListShow(true)/setListShow(false).
If i comment this methods, the clicks works fine, but a loading message was showed. It force me to extend from Fragment, instead of list fragment

I dont think so, but @ifoche maybe it is related with the planning tab problem.

**Comment by ifoche** [comment]
@idelcano, yes I think that for monitor tab, there is no need at all of a list fragment. That was something only needed for showing a list and, as you're not showing any list in that fragment, you can do it there without any problem. The problem of planning tab is different, because there, we're using the list capabilities of a list fragment, I think, but thank you anyway, I'll take a look to it.

**Comment by idelcano** [comment]
@ifoche sorry! I forgot comment it.  
It is finished, but i am waiting for do the PR becouse i think the dropdown style can be changed.
I will upload a pic in flew mins. And maybe you can suggest me something.
