### ISSUE TITLE
Planning Tab

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#639]

**Comment by ifoche** [comment]
![planning_tab](https://cloud.githubusercontent.com/assets/10931645/11702202/1aacbca8-9ed5-11e5-950a-b6ff943d10a8.png)

**Comment by ifoche** [comment]
- UI tasks
   - [ ] Layout with list/table appearance
   - [ ] Dropdown viewing logic
- [ ] Surveys classification: Never Assessed / Overdue / next 30 days / future 
- [ ] New calendar picker component
- [ ] Productivity classification (DB change and attribute pull, mocked as not yet in server)
- Actions and workflow
   - [ ] Implement next QA algorithm (depending on productivity and score class, see chart)
   - [ ] Schedule and reschedule logic (with annotations)
   - [ ] Survey creation shortcut with OrgUnit and Program automatic selection
   - [ ] Survey edition shortcut when in progress survey
   - [ ] Filters and reordering actions

**Comment by ifoche** [comment]
![planning_algorithm](https://cloud.githubusercontent.com/assets/10931645/11784636/b3673562-a27d-11e5-9b58-7a6633d722f2.png)

**Comment by ivanarrizabalaga** [comment]
@ifoche

Several minor questions related to the order of items:

 - As a general rule items are ordered as a queue where whatever it comes next it goes higher but...

 - Are different programs for the same org unit grouped together? Or are they displayed according to their scheduled date no matter what orgunit it is?

 - In case they are grouped, how are these groups ordered?

I would say that since every couple (orgunit + program) is independent there should be a row for each couple and order always according to its scheduled date (and alphabetically as a 2nd criteria) but I dont know.

**Comment by ivanarrizabalaga** [comment]
@ifoche I've push the working branch *planning_tab*.

**Comment by ifoche** [comment]
ok, thanks!!

**Comment by ivanarrizabalaga** [comment]
@ifoche nothing is better than sleeping, I've already solved the weird issue.

A ListFragment does not require an explicit ListView in the xml because it is automatically added to the layout just for being a ListFragment.

Ready to keep on working with the rest...

**Comment by ifoche** [comment]
@ivanarrizabalaga excellent!!! I'm glad to hear that. Thank you for the
effort

**Comment by ivanarrizabalaga** [comment]
@ifoche I've reviewed the code and push the changes to the branch.

Some minor stuff still need discussion, I guess we better talk about it in 30min.

**Comment by ifoche** [comment]
ok, thank you
