### ISSUE TITLE
Introduce RadioButton / Dropdown representation

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#71]

**Comment by josemp10** [comment]
Also, notice that the rendering of the RadioButtons could be horizonal or vertical. This means that we are going to have other input value in our database, and we need to check in the code if the componente are going to be showed  verticaly or horizontally

**Comment by adrianq** [comment]
@ifoche drop me a line when you are around so we can discuss if this task is fully done.

**Comment by adrianq** [comment]
@josemp10 this task is done. In order to allow two different types of orientation I have created two answer outputs:
            RADIO_GROUP_HORIZONTAL = 8,
            RADIO_GROUP_VERTICAL = 9;

and example of the Answers.csv file will be:
52;'Yes1No0Vertical';8
53;'Yes1No0Horizontal';9

However, I have implemented it in a generic way. So it will work for n options (not only for yes/no radiobuttons). 

If this problem about component orientation becomes sth common we can think about a more elegant way to implement it. Let me know if you think there is any problem with this approach.
