### ISSUE TITLE
Introduce a way to reset the test state at the beginning of each test

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#779]

**Comment by idelcano** [comment]
The actual solution to reset the test is:
@AfterClass force backbutton exit of the application.
But, sometimes not work, and @Before force init in loginActivity(using backbutton logic too).

I found other solution to close all the activitys, but not work good. I think the way to close Dhis threah is closing the app with backbutton.

@ifoche maybe you can try in your computer before the Monday, for know if i need continue working looking other solutions ( It work for me now in android emulator)
[PR](https://github.com/EyeSeeTea/malariapp/pull/761)


Some problems with push tests:
1. For me, the wait for pull needs 20 seconds in  all the test. Ivan had 15.(Maybe we need change it in function of the computer...)

2. Push error never works. Becouse the flow aplication is now stopping on pull if with user without permissions, and never join in dashboard and never sent the survey.

3. Push ok not work in screens with the "No" option not show in the screen(I take a screenshoot), I add temporaly try{} catch and it works sending 0 values(not had compulsory questions) . Is a problem with the "No" textview.

![layout_view](https://cloud.githubusercontent.com/assets/5302538/13194334/a2781dca-d78e-11e5-9abd-975ca573a44e.png)

![layout_view](https://cloud.githubusercontent.com/assets/5302538/13194334/a2781dca-d78e-11e5-9abd-975ca573a44e.png)

**Comment by idelcano** [comment]
@Ifoche i uploaded Pull_test branch again. ( And i considered its finished).

Posible problems:
Copy paste: "Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong."
Solution: Unlock the screen.

Other problems if the application fails in pull/push is necessary increment the pull time. 


I did a refactor and fixing some problems in appexit() and gotologin() method, and i added a constant value for set the iddletimeout throw(setIdlingResourceTimeout) and for set the waitforpull time becouse i think it maybe changes between computers, and is more easy to change if is necesary set an upper time sleep.

The logic is:
If the test finish, the app is closed in  @afterclass(using logout/backpress app buttons and workflow).
If the test start, before start, the @before option set the aplication in loginactivity.


I want comment other thing.
I had some problems with DB in some of my emulators:

For example, i had installed in some emulators the  application without OrganisationUnitLevels table. But with the DB in the last version.
In this escenary, the new pojo(OrganistaionUnitLevel) is not created... Becouse we have installling the application in the last DB version. And the new OrganisationUnitLevel pojo is never translated to DB.

It should be solved increment the DB version (without migration file), or simply removing and reinstalling the app.
I think only the development team should be this problem.
