### ISSUE TITLE
When parent question hide its children, ask for confirmation to delete the children values

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#845]

**Comment by idelcano** [comment]
@ifoche sorry, i am having problems with this task.
The problem was:

I need create a dialog from a Activity(for example from DashboardActivity, it is the activity open when survey fragment is display), becouse the radiolistener not have activity  context to call the dialog.

But i have two problems.
The first is the dialog, is showed too late.. 
It is like in other thread. 
When the dialog is showed in the screen, all the actions was ran time before.
And the second, i need get the response of the dialog from a static variables and i need stop the onCheckedChanged action.


I was trying setting a clicklistener in the radiobuttons button , but the click is running before onCheckedChanged.

I did for try to understood the problem:
I try to do:
show dialog
thread sleep(isdialoganswered?)
actions.
But the dialog never was showed.

if the secuence is:
show dialog
actions

The app do:
actions
...
show dialog

I was trying now using other listeners for the buttons if the radiobutton question has childs.
For example, i´m trying, setOnTouchListener (here i should the dialog) and setOnClickListener(if the dialog was showed, run it and click the button)
The order in execution are Touchlistener CheckedChangedListener and ClickListener.
I need show the dialog in Touchlistener, but wait for it before run the others listeneres.

This is taking me so many time trying ways to show the dialog and get the values.

Do you have any idea how can i do it?
Do you prefer i change of issue and still think about it?
Or is it more important than the others and it needs be finished it first?

thanks!

**Comment by ifoche** [comment]
@idelcano I need you to upload whatever you could have about this issue to a branch and move to another issue. And please first move back again to the parent-questions progress wheel task as it is not yet working (I'll explain there why not). Just to give you an idea about the pressure that we have, tonight we're releasing the last version that should contain every bug solved, so please if you find problems today working on an issue, comment it and move quickly to the next one, I'll be around to try to solve those you leave behind.

**Comment by idelcano** [comment]
@ifoche the branch is (add_confirm_before_close_childquestions)
https://github.com/EyeSeeTea/malariapp/tree/add_confirm_before_close_childquestions
