### ISSUE TITLE
Monitoring total amount of surveys is wrong

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#881]

**Comment by ifoche** [comment]
Is like it contains the never assessed surveys and the scheduled ones or something like that, but the number is extremely high to be real.

**Comment by idelcano** [comment]
@ifoche The problem is related with the event state column ( COMPLETED / ACTIVE ) in the server. 
I only can see events with status "active" in the web. But we're pulling both.

For example (program CervicalCancer):
We have 28 surveys in facility 1 and 12 in facility 2. But we have 57 in total in our dhis DB. 17 extra events with "completed" state.

[facility test 1 program Cervical Cancer](
https://hnqis.psi-mis.org/api/events?program=g5JtETComKt&orgUnit=QS7sK8XzdQc)
[facility test 2 program Cervical Cancer](
https://hnqis.psi-mis.org/api/events?program=g5JtETComKt&orgUnit=xNLfNAtUXfA)




I thought three possible solutions.
1. Add a "serverStatus" column in the Survey Pojo. 
And ignore the surveys with the server status as "COMPLETED" in the monitor charts.
2. Do not save the COMPLETED events.
3. Or just don't do nothing if we should show the COMPLETED surveys too.
