### ISSUE TITLE
Dates problem whenever an assessment is created offline

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#883]

**Comment by ifoche** [comment]
In Tanzania we experimented a very strange problem. We created an assessment on day 15-3 and in the improve module we could read 14-3. However when we connected the tablet to internet and it was sent, then the date was updated into 15-3. We have to manage very clearly which are the dates we're using for what. We need also to review which is the mapping from the server dates to our dates. Apparently, completion date in the server has another meaning, and we thought that it was not being used.

**Comment by idelcano** [comment]
It was "solved" in my last PR(go_to_feedback). 
Waiting for resolve the real completion date problem.

The problem was we was showing the event date in the "Completion Date" column on the Improve tab.
I changed this date from event date to completion date. 

The dates workflow are the next:

The event date:
It is new Date when a survey is created.
It is new Date when a survey is pushed.
If the push fail, it can be changed in next push.

The completion date flow:
It is new Date when a survey is created.
It is overwrite by new Date when a survey is closed, or the application is closed.

The creation date flow:
It is new Date when we start a survey from the SurveyPlanner.
Never changes.

The Scheduled date flow:
When a survey is removed, a new date is created from date removed survey.
Or, it is created when a survey(with program+orgunit combination) is not in planning tab.


Of course, all the dates can be downloaded from the events.

**Comment by ifoche** [comment]
So #866 solves this (just to link this issue to that PR). However, I have just a few comments on your last one:
- Event date. This is the same as completion date, since what we talked yesterday, isn't it? In my opinion it should be null while the survey is not yet completed and set to new Date when the survey is marked as completed. During the pull process it should be set to the event date in the DHIS2 database.
- Creation date. It should take the "new Date()" when we start a survey from the SurveyPlanner, but also when we create it using the Assess + button. Is it like that?
- Scheduled date flow: I didn't understand this part. Can you explain it in more detail?

**Comment by idelcano** [comment]
Event date: it is solved and changed to work like you said now.
Creation date: It's alright.
Scheduled date: changed to work from the completion date.
